### ISSUE TITLE
Unable to try api

### ISSUE THREAD

**Issue by itzkabs** [nate01776/swaggerhub-doc-portal#3]
Hi there, I am trying to execute the API with input (textbox) but looks like every time I hit the execute button, textbox gets cleared. Am I doing anything wrong ? I tried your demo site as well and able to reproduce the issue.

**Comment by nate01776** [comment]
@itzkabs Seeing something similar as well - on my side

- The field is displayed in the documentation, but text cannot be inputted until the 'Try It Out' button is selected. 
- Values can be added to the field - but it won't make a call out to the example service. 
- For calls with predefined lists (such as /pet/findByStatus on the demo site main page) - the Try It Out appears to work as expected.

Will look into this, thanks for bringing it up.

**Comment by nate01776** [comment]
@itzkabs The problem should be resolved on the demo page as well as running locally. I will have to go back and update to blog/documentation but please reach out if you are still having issues.
